### ISSUE TITLE
require method

### ISSUE THREAD

**Issue by saitam1** [scott-lin/install-npm-version#3]
Is it possible to use the installed package version in a way like this:

var package_old = inv.require('packagenameolder@1.0.0');
var package_new = inv.require('packagenamenewer@1.0.1');

**Comment by scott-lin** [comment]
I'd like to explore your use case more. Is there a reason why you can't use the native `require` function like the example below as opposed to install-npm-version wrapping it?

```
import inv = require('install-npm-version');

inv.Install('chalk@2.4.0', { Overwrite: true });
inv.Install('chalk@2.4.1', { Overwrite: true });
        
let oldPackage = require('chalk@2.4.0');
let newPackage = require('chalk@2.4.1');

console.log(oldPackage.blue('Blue'));
console.log(newPackage.yellow('Yellow'));
```

**Comment by scott-lin** [comment]
I'm going to close this issue since I haven't heard back. Feel free to respond to my last inquiry for more details if you still feel this enhancement belongs in this code base.
