### ISSUE TITLE
FileSystem: startsWith destinationDirectoryPaths-filter filters similar named paths

### ISSUE THREAD

**Issue by Azlond** [scott-lin/install-npm-version#4]
**Describe the Issue**
If a module has two similar named folders, the `copyFiles()` call from `inv.Install()` -> `CopyPackageDependencies()` -> `CopyFiles()` can accidentally filter out valid paths. This causes 
`Error: ENOENT: no such file or directory, copyfile '__path__/util/convert' -> '__new_path__/util/convert'`

**Steps to Reproduce the Issue**
If you have two or more similar named folders, e.g. _util_ and _utilities_, [_/path_to/util, /path_to/utilities_]
FileSystem.ts line 33 will return false for index 0.
`return !array[index + 1].startsWith(directoryPath);`

**Expected Behavior**
It should only filter out identical paths

**Environment**
 - OS: [Linux Mint 19.1 Tessa]
 - Node: [e.g. v10.15.1]

**Additional Context**

**Screenshots**

**Comment by scott-lin** [comment]
Thanks for reporting this issue, Jan. Can you share your install-npm-version usage command, so that I can test the fix I will develop with more confidence? I'm most interested in the package you're trying to install, but the full command would help.

**Comment by Azlond** [comment]
The package is sadly not publicy accessible, as it is in our internal verdaccio npm repo.
We're simply using `inv.Install('ssc', { Verbosity: 'Debug' });`. SSC in turn has dependencies (e.g. an internal `locale` package), which are installed upon usage of the `Install`-command. `locale` then has the aforementioned `utils` and `utilities`folders where the error occurs.
If you need a beta tester give me a shout, I'd gladly test it for my case.

**Comment by scott-lin** [comment]
No problem. If you could try the beta fix, I'd appreciate it.

https://www.npmjs.com/package/install-npm-version/v/1.0.4-beta.0

**Comment by Azlond** [comment]
The beta version fixes it, everything works as expected now.

**Comment by scott-lin** [comment]
Thanks for confirming! I'll get the fix integrated into master and push an official package at my earliest. In the meantime, feel free to continue using the beta package to unblock yourself.
