### ISSUE TITLE
Package is installed without deps

### ISSUE THREAD

**Issue by KirillYoYo** [scott-lin/install-npm-version#7]
Package is installed without deps

**Steps to Reproduce the Issue**
1. run `inv -- d3@4 --destination d3-v4 --overwrite`
2. Check d3-v4 folder in 'node_modules'
3. In d3-v4 'node_modules' is empty, you must run `npm i` from 'd3-v4' directly

**Environment**
Kubuntu 18.04
Node 12.13.0

**Comment by scott-lin** [comment]
Can you please confirm the command you are using? `inv -- d3@4 --destination d3-v4 --overwrite` as you posted is not valid.

Please also run with the `--debug` option as well and post the error.

**Comment by KirillYoYo** [comment]
@scott-lin steel node_modules empty
`
$ inv d3@4 --destination d3-v4 --overwrite --debug
undefined
Settings: {"Destination":"d3-v4","NpmPackage":"d3@4","Overwrite":true,"UseLocalNpmrcFile":true,"WorkingDirectory":"/home/k/PR/flybridge","Verbosity":"Debug","NodeModulesPath":"/home/k/PR/flybridge/node_modules"}
Install Path: /home/k/PR/flybridge/node_modules/d3-v4
Temporary staging directory created at "/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ".
Spawning child process to install d3@4 at "/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ".
npm WARN saveError ENOENT: no such file or directory, open '/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ/package.json'
npm WARN .install-npm-version-temp-CSNbqJ No description
npm WARN .install-npm-version-temp-CSNbqJ No repository field.
npm WARN .install-npm-version-temp-CSNbqJ No README data
npm WARN .install-npm-version-temp-CSNbqJ No license field.

+ d3@4.13.0
added 36 packages from 5 contributors and audited 101 packages in 2.382s
found 0 vulnerabilities

Package name is "d3".
Copying d3 package dependencies to "/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ/node_modules/d3/node_modules".
Deleted existing directory at final installation path "/home/k/PR/flybridge/node_modules/d3-v4".
Copying staged package "/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ/node_modules/d3" to final destination "/home/k/PR/flybridge/node_modules/d3-v4".
Installed d3@4 to "/home/k/PR/flybridge/node_modules/d3-v4".
Temporary staging directory deleted at "/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ".
Done in 3.93s.
`
- whats what? Script cant find 'package.json' file?

**Comment by scott-lin** [comment]
From the logs, `npm install` command is having issues when installing `d3@4` package. I do not have a Kubuntu environment where I can reproduce the issue, so I would need you to help me narrow down the npm issue.

- What version of npm are you using?

- Can you manually try running npm in a similar manner that the tool is doing? By this I mean, create path "/home/k/PR/flybridge/node_modules/.install-npm-version-temp-CSNbqJ" and try running `npm install d3@4" at this location to verify it succeeds or fails.

**Comment by scott-lin** [comment]
Closing this issue as I have not heard back from the author in four months.
