### ISSUE TITLE
Destination path incorrect when copying .npmrc

### ISSUE THREAD

**Issue by vsetka** [scott-lin/install-npm-version#9]
There is a bug in `.npmrc` copy logic where the file is copied to an incorrect destination. The LoC in question:
https://github.com/scott-lin/install-npm-version/blob/26d223882b69d1f5c5feb38d317d1bfbd492d3ca/src/FileSystem.ts#L71
The `destinationPath` variable should also include `.npmrc` in the path, for example:
```javascript
fs.copyFileSync(npmrcFilePath, path.join(destinationPath, '.npmrc'));
```
Otherwise, we get an exception: `Error: EISDIR: illegal operation on a directory`

Node version: **14.1.0** (but from what I can see in the docs, nothing has changed in `copyFileSync` function so this was likely a problem in previous versions as well).

I can also create a PR, but since it was such a small change/fix, I thought I'd just write it up all in an issue.

**Comment by scott-lin** [comment]
Thanks for reporting, @vsetka. I have created a pull request with the fix. I will give you a chance to review/approve and validate no repro for your environment before I merge.

**Comment by vsetka** [comment]
Hey @scott-lin, looks good! Thank you for the quick reaction.
